// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:flutter/src/foundation/diagnostics.dart' as prefix3;
import 'package:flutter/src/foundation/key.dart' as prefix4;
import 'package:flutter/src/widgets/framework.dart' as prefix5;
import 'package:flutter_organized_widgets/model/lib_stuff.dart' as prefix0;
import 'package:flutter_organized_widgets/test.dart' as prefix1;
import 'package:meta/meta.dart' as prefix2;

// ignore_for_file: unnecessary_const
// ignore_for_file: prefer_collection_literals
// ignore_for_file: prefer_adjacent_string_concatenation

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'TestWidget',
            r'.TestWidget',
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 2, 4],
            const <int>[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 2, 3],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) => ({key, test}) =>
                  b ? prefix1.TestWidget(key: key, test: test) : null
            },
            0,
            0,
            const <int>[],
            const <Object>[
              prefix0.reflector,
              const prefix0.Defaults(const [], positioned: const {})
            ],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'test', 33797, 0, const prefix0.Reflector(), -1,
            1, 1, const <int>[], const []),
        r.VariableMirrorImpl(r'key', 33797, null, const prefix0.Reflector(), -1,
            2, 2, const <int>[], const []),
        r.MethodMirrorImpl(
            r'build',
            131074,
            0,
            -1,
            3,
            3,
            const <int>[],
            const <int>[0],
            const prefix0.Reflector(),
            const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 3),
        r.MethodMirrorImpl(r'', 128, 0, -1, 0, 0, const <int>[],
            const <int>[1, 2], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 1, 1, const <int>[],
            const <int>[3], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(
            r'toString',
            131074,
            null,
            -1,
            4,
            4,
            const <int>[],
            const <int>[4],
            const prefix0.Reflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, null, null, null, null,
            const <int>[], const <int>[5], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 5, 5, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, null, -1, 6, 6,
            const <int>[], const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(
            r'toStringShort',
            131074,
            null,
            -1,
            4,
            4,
            const <int>[],
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'toDiagnosticsNode',
            131074,
            null,
            -1,
            7,
            7,
            const <int>[],
            const <int>[6, 7],
            const prefix0.Reflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'debugFillProperties',
            262146,
            null,
            null,
            -1,
            -1,
            const <int>[],
            const <int>[8],
            const prefix0.Reflector(),
            const <Object>[override]),
        r.MethodMirrorImpl(
            r'toStringShallow',
            131074,
            null,
            -1,
            4,
            4,
            const <int>[],
            const <int>[9, 10],
            const prefix0.Reflector(),
            const []),
        r.MethodMirrorImpl(
            r'toStringDeep',
            131074,
            null,
            -1,
            4,
            4,
            const <int>[],
            const <int>[11, 12, 13],
            const prefix0.Reflector(),
            const []),
        r.MethodMirrorImpl(
            r'debugDescribeChildren',
            4325378,
            null,
            -1,
            8,
            9,
            const <int>[7],
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[prefix2.protected]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 16),
        r.MethodMirrorImpl(
            r'createElement',
            131074,
            null,
            -1,
            10,
            10,
            const <int>[],
            const <int>[],
            const prefix0.Reflector(),
            const <Object>[override])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'context', 32774, 2, const prefix0.Reflector(),
            -1, 11, 11, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'key', 45062, 4, const prefix0.Reflector(), -1,
            2, 2, const <int>[], const [], null, #key),
        r.ParameterMirrorImpl(r'test', 45062, 4, const prefix0.Reflector(), -1,
            1, 1, const <int>[], const [], null, #test),
        r.ParameterMirrorImpl(r'other', 16390, 5, const prefix0.Reflector(),
            null, null, null, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'minLevel',
            47110,
            6,
            const prefix0.Reflector(),
            -1,
            12,
            12,
            const <int>[],
            const [],
            prefix3.DiagnosticLevel.debug,
            #minLevel),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            7,
            const prefix0.Reflector(),
            -1,
            13,
            13,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'name', 45062, 11, const prefix0.Reflector(), -1,
            4, 4, const <int>[], const [], null, #name),
        r.ParameterMirrorImpl(r'style', 45062, 11, const prefix0.Reflector(),
            -1, 14, 14, const <int>[], const [], null, #style),
        r.ParameterMirrorImpl(
            r'properties',
            32774,
            12,
            const prefix0.Reflector(),
            -1,
            15,
            15,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'joiner', 47110, 13, const prefix0.Reflector(),
            -1, 4, 4, const <int>[], const [], ', ', #joiner),
        r.ParameterMirrorImpl(
            r'minLevel',
            47110,
            13,
            const prefix0.Reflector(),
            -1,
            12,
            12,
            const <int>[],
            const [],
            prefix3.DiagnosticLevel.debug,
            #minLevel),
        r.ParameterMirrorImpl(
            r'prefixLineOne',
            47110,
            14,
            const prefix0.Reflector(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            '',
            #prefixLineOne),
        r.ParameterMirrorImpl(
            r'prefixOtherLines',
            45062,
            14,
            const prefix0.Reflector(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            #prefixOtherLines),
        r.ParameterMirrorImpl(
            r'minLevel',
            47110,
            14,
            const prefix0.Reflector(),
            -1,
            12,
            12,
            const <int>[],
            const [],
            prefix3.DiagnosticLevel.debug,
            #minLevel)
      ],
      <Type>[
        prefix1.TestWidget,
        bool,
        prefix4.Key,
        prefix5.Widget,
        String,
        int,
        Type,
        prefix3.DiagnosticsNode,
        const m.TypeValue<List<prefix3.DiagnosticsNode>>().type,
        List,
        prefix5.StatelessElement,
        prefix5.BuildContext,
        prefix3.DiagnosticLevel,
        Invocation,
        prefix3.DiagnosticsTreeStyle,
        prefix3.DiagnosticPropertiesBuilder
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toStringShort': (dynamic instance) => instance.toStringShort,
        r'toDiagnosticsNode': (dynamic instance) => instance.toDiagnosticsNode,
        r'debugFillProperties': (dynamic instance) =>
            instance.debugFillProperties,
        r'toStringShallow': (dynamic instance) => instance.toStringShallow,
        r'toStringDeep': (dynamic instance) => instance.toStringDeep,
        r'debugDescribeChildren': (dynamic instance) =>
            instance.debugDescribeChildren,
        r'key': (dynamic instance) => instance.key,
        r'createElement': (dynamic instance) => instance.createElement,
        r'build': (dynamic instance) => instance.build,
        r'test': (dynamic instance) => instance.test
      },
      {},
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://0/'),
            const prefix0.Reflector(), const <int>[], {}, {}, const [], null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
